import { Product } from "@/app/types/index";

export const products: Product[] = [
  {
    id: 1,
    name: "Dark Horse – Brazil",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081317/coffee-co/004_f0odqe.png",
    price: 34,
    int: 4,
    text: "Indulge in the bold and robust flavors of our Dark Horse blend sourced from the lush coffee plantations of Brazil. This exquisite coffee offers a rich, full-bodied taste with subtle hints of cocoa and nuts. It's perfect for those who crave a deep and satisfying coffee experience.",
  },
  {
    id: 2,
    name: "Tropic Thunder – Colombia",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081317/coffee-co/006_mufqwc.png",
    price: 34,
    int: 3,
    text: "Embark on a journey to the heart of Colombia with our Tropic Thunder blend. This coffee boasts bright acidity and a delightful fruitiness, reminiscent of tropical paradise. With its vibrant flavor profile, it's the ideal choice for those seeking a taste of exotic adventure in every cup.",
  },
  {
    id: 3,
    name: "Morning Bliss – Ethiopia",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081317/coffee-co/008_qeimea.png",
    price: 34,
    int: 2,
    text: "Start your day with the ethereal flavors of Morning Bliss, a coffee blend straight from the highlands of Ethiopia. Known for its bright citrus notes and floral undertones, this coffee is like a morning symphony for your taste buds, providing a refreshing and invigorating start to your day.",
  },
  {
    id: 4,
    name: "Oasis Serenity – Yemen",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081317/coffee-co/005_sqtapc.png",
    price: 34,
    int: 2,
    text: "Discover tranquility in a cup with our Oasis Serenity blend, originating from the serene landscapes of Yemen. This coffee offers a unique combination of spiciness and earthiness, creating a harmonious blend that soothes the soul. It's a true oasis of flavor amidst the chaos of your day.",
  },
  {
    id: 5,
    name: "Golden Harvest – Peru",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081317/coffee-co/001_kuj1sq.png",
    price: 39,
    int: 3,
    text: "Delight in the golden treasures of the Peruvian coffee fields with our Golden Harvest blend. This medium-roast coffee features a smooth and balanced profile with subtle notes of caramel and nuts. It's a comforting and reliable choice for coffee enthusiasts.",
  },
  {
    id: 6,
    name: "African Spice – Kenya",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081318/coffee-co/002_zdiqng.png",
    price: 39,
    int: 4,
    text: "Experience the vibrant and spicy flavors of Africa with our African Spice blend, sourced exclusively from Kenya. This coffee boasts a lively acidity and bold flavors of black currant and spices. It's a true celebration of African coffee culture.",
  },
  {
    id: 7,
    name: "Coffee-Co Special",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081317/coffee-co/003_bcg7ck.png",
    price: 37,
    int: 3,
    text: "Our Coffee-Co Special blend is a carefully crafted masterpiece that brings together beans from various regions. This complex blend offers a well-rounded flavor profile with hints of chocolate, caramel, and a touch of citrus. It's a crowd-pleaser that caters to a wide range of coffee preferences.",
  },
  {
    id: 8,
    name: "Coffee-Co Special Decaf",
    gr: "250 GR",
    img: "https://res.cloudinary.com/djlyhp6vr/image/upload/v1694081318/coffee-co/007_fqwksy.png",
    price: 37,
    int: 3,
    text: "For those who prefer to savor the rich taste of coffee without the caffeine, our Coffee-Co Special Decaf blend is the perfect choice. It retains the same exceptional flavor profile as our regular special blend, with the added benefit of being caffeine-free. Enjoy the warmth and comfort of coffee anytime, day or night, without the jolt.",
  },
];
